config/routes.rb
# frozen_string_literal: true

# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
#
Rails.application.routes.draw do
  # Defines the root path route ("/")
  # root "articles#index"

  # The controller is called "pages" (actually pages.controller.rb) and the
  # action to be invoked is call home , so the pages controller needs a method called home
  #     root 'articles#index'
  root 'pages#home'

  # Adding an About (static) page:
  # The below maps the uri provided by the  Rails Get action to the controller given by
  # "pages" and the "about" action within that contoller
  get 'about', to: 'pages#about'

  # Provides the basic CRUD routes [from base class] for articles
  # To expose the routes incrementally or as a subset, use the ",only" modifier.
  # resources :articles, only: %i[show index new create edit update destroy]
  # Expose all routes of the articles resource
  #
  # Expose the routes for comments as nested by resources.
  # This relfects the 1:many relationship and Rails will provide the parent article with each
  # comment route
  resources :articles do
    resources :comments
  end

  # Routes for User actions
  get 'signup', to: 'users#new'

  # The form_with statement in users/_form.html.erb needs to know where to post
  # the form.  Since we pass it model: @user, it looks for users_path.
  # Since the form is invoked by the "new" method we complete the new user creation
  # by sending the form's data to the create method:
  # post 'users', to: 'users#create'
  # Alternatively, the resources statement assigns all the standard routes.  But we
  # want the "new" method to be invoked by signup [as above] so we can omit it from the
  # resources statement
  resources :users, except: [:new]

  # Login actions - to be managed by the sessions controller
  #  1.  Login validation
  get 'login', to: 'sessions#new'
  #
  # 2.  Create a session based on successful login.
  #     Recall the HTTP verb "post" denotes creation of a new resource
  post 'login', to: 'sessions#create'
  #
  # 3. Logout and thus delete a user session
  delete 'logout', to: 'sessions#destroy'
  #
  # ----  Routes for categories
  resources :categories
end

app/models/category.rb
# frozen_string_literal: true

# Class Category serves as the Rails model for entity "category" in this blog app
# A category has a many-many atssocation with an article
#  As per https://guides.rubyonrails.org/association_basics.html#the-has-many-association
#
class Category < ApplicationRecord
  has_many  :article_categories
  has_many  :articles, through: :article_categories, dependent: :destroy
  validates :name,  presence: true, uniqueness: true,
                    length: { minimum: 3, maximum: 25 }
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

# This is the controller for the categories resource
class CategoriesController < ApplicationController
  # before_action :require_admin, except: %i[index show]
  before_action :logged_in?, except: %i[index show]

  def new
    # Create a new category object immediately upon entry of this method so that
    # a valid category object exists when the Show etc. pages are first entered.
    # Otherwise, the error trapping done there will fail
    @category = Category.new
  end

  def create
    @category = Category.new(whitelist_category_params)

    if @category.save
      # Generate a confirmation message for the user.
      flash[:notice] = 'Category was created successfully.'
      redirect_to categories_path

    else
      # Error trapping
      # Re-render the "new" category page.
      # Because the save returned false, the error trapping on the "new" page
      # will display the errors
      render 'new', status: :unprocessable_entity

    end
  end

  def show
    # Instantiate the current category as passed from the browser via the Index page
    @category = Category.find(params[:id])
    # In preparation for the category show page, get a list of the articles in this category.
    # Note @articles, here, is an array, not an object
    @articles = @category.articles.paginate(page: params[:page], per_page: 5)
                         .order('created_at DESC')
  end

  def index
    # Utilizing the will_paginate gem to include pagination as this code was
    # @categories= Category.all, which could return many rows
    @categories = Category.paginate(page: params[:page], per_page: 16).order('name ASC')
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    # Instantiate the current category as passed from the browser via the Edit page
    @category = Category.find(params[:id])

    if @category.update(whitelist_category_params)
      #
      # Generate a confirmation message for the user.
      flash[:notice] = 'Category was updated successfully.'

      # Now that the category is updated, we need to tell Rails what to do.
      redirect_to category_path

    else

      # Error trapping
      # Re-render the "edit" article page.
      # Because the save returned false, the error trapping on the "edit" page
      # will display the errors
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    # Instantiate the current category as passed from the browser
    @category = Category.find(params[:id])

    if @category.destroy
      #
      # Generate a confirmation message for the user.
      flash[:notice] = 'Category was deleted successfully.'

      # Now that the article is deleted, we need to tell Rails what to do.
      # Convention would take the user to the articles list page
      #
      # Note:  We knew that the path to the articles listing page is articles_path because
      # from $rails routes --expanded we see:
      # [ Route 3 ]-----------------------------------------------------------------
      # Prefix            | articles  <-- Therefore the path is articles_path
      # Verb              | GET
      # URI               | /articles(.:format)
      # Controller#Action | articles#index

      redirect_to categories_path

    else

      # Error trapping
      # Re-render the "edit" article page.
      # Because the save returned false, the error trapping on the "edit" page
      # will display the errors
      render 'edit', status: :unprocessable_entity
    end
  end

  private

  def whitelist_category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if logged_in? && @current_user.admin
      true
    else
      flash[:alert] = 'Categories can only be created by Admin-level users'
      redirect_to categories_path
    end
  end
end

app/views/categories/_category.html.erb
<%= link_to category.name,  category_path(category),
                            class: "badge rounded-pill mybadge-background mybadge-text" %>

app/views/categories/_category_list.html.erb
<div class="container text-center">
  <div class="row row-cols-5">
    <% @categories.each do |category| %>
      <div class="col mt-2">
        <div class="card border-dark mb-3 shadow mycategory-background">
          <div class="card-text">
            <%= link_to category.name, category_path(category),
                                      class: 'link-dark text-decoration-none' %>
          </div>
          <div class="fw-light">
            <%= pluralize(category.articles.count, 'article') %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/_form.html.erb
<!--  Use form_with helper to aid with the form for creating a new category and editing an
      existing category. e.g.,
        - For a new category, the "submit" button will have the label "Create Category"
        - For an existing category, Rails will pre-populate the edit form with the category's contents and label the "submit" button as "Update Category".
        - My word...

        Because the "new" and "edit" actions need the category object to know which category
        is being edited, as per the route, the category id is provided in the URI from the browser.
        Rails and the forms helper know all this, so all we have to do is pass along
        model: @category and Rails will access the id from the category object.

        local :true speficies form_with to use local http and not ajax
-->
<div class="container row justify-content-center col-10">

  <%= form_with(model: @category, local: true, class: "shadow p-3 mb-3 bg-grey rounded") do |f| %>

    <div class="form-group row">
      <%= f.label :name, "Category name:", class: "col-2 col-form-label" %>
      <div class="col-8">
        <%= f.text_field :name, class: "form-control shadow rounded", autofocus: "autofocus",
                                placeholder: "Enter a category name" %>
      </div>
    </div>

    <div class="mt-2 text-center">
      <%= f.submit %>
    </div>

  <% end %>

</div>

app/views/categories/edit.html.erb
<div class="container">
  <h6 class="text-center mt-2">Rename this Category</h6>
</div>

<%= render 'shared/error_msgs', obj: @category %>
<%= render 'categories/form' %>

<div class="text-center mt-2 mb-3">
  <%= link_to '[ Cancel and return to Category]', category_path(@category),
              class: "text-decoration-none" %>
</div>

app/views/categories/index.html.erb
<h2 class="text-center mt-2">Blog Categories</h2>

<!--Utilizing the will_paginate gem to include pagination in the rendering of the categories listing - just because ... -->
<div class="apple_pagination">
  <%= will_paginate @categories, :container => false %>
</div>

<%= render 'categories/category_list' %>

<div class="apple_pagination">
  <%= will_paginate @categories, :container => false %>
</div>

app/views/categories/new.html.erb
<div class="container">
  <h4 class="text-center mt-2">Create a New Article Category</h4>
</div>

<%= render 'shared/error_msgs', obj: @category %>
<%= render 'categories/form' %>

<div class="text-center mt-2 mb-3">
  <%= link_to '[ Cancel and return to Categories]', categories_path,
               class: "text-decoration-none" %>
</div>

app/views/categories/show.html.erb
<h4 class="text-center mt-2"><%= "Category: #{@category.name}" %></h4>

<div class="text-center d-block mt-2">
	<% if logged_in? && current_user.admin? %>
		<%= link_to "Edit", edit_category_path(@category),
								class: "btn btn-outline-primary btn-sm" %>
		<%= link_to "Delete", category_path(@category),
								class: "btn btn-outline-danger btn-sm",
								data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
	<% end %>
</div>

<% if @category.articles.count > 0 %>
  <h5 class="text-center border mt-4">Articles in this category:</h5>
<% end %>

<!--Utilizing the will_paginate gem to include pagination in the rendering of the articles listing -->
<div class="apple_pagination">
	<%= will_paginate @articles, :container => false %>
</div>

<%= render 'articles/article' %>

<!--Utilizing the will_paginate gem to include pagination in the rendering of the articles listing -->
<div class="apple_pagination">
  <%= will_paginate @articles, :container => false %>
</div>