config/routes.rb
# frozen_string_literal: true

# Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
#
Rails.application.routes.draw do
  # Defines the root path route ("/")
  # root "articles#index"

  # The controller is called "pages" (actually pages.controller.rb) and the
  # action to be invoked is call home , so the pages controller needs a method called home
  #     root 'articles#index'
  root 'pages#home'

  # Adding an About (static) page:
  # The below maps the uri provided by the  Rails Get action to the controller given by
  # "pages" and the "about" action within that contoller
  get 'about', to: 'pages#about'

  # Provides the basic CRUD routes [from base class] for articles
  # To expose the routes incrementally or as a subset, use the ",only" modifier.
  # resources :articles, only: %i[show index new create edit update destroy]
  # Expose all routes of the articles resource
  #
  # Expose the routes for comments as nested by resources.
  # This relfects the 1:many relationship and Rails will provide the parent article with each
  # comment route
  resources :articles do
    resources :comments
  end

  # Routes for User actions
  get 'signup', to: 'users#new'

  # The form_with statement in users/_form.html.erb needs to know where to post
  # the form.  Since we pass it model: @user, it looks for users_path.
  # Since the form is invoked by the "new" method we complete the new user creation
  # by sending the form's data to the create method:
  # post 'users', to: 'users#create'
  # Alternatively, the resources statement assigns all the standard routes.  But we
  # want the "new" method to be invoked by signup [as above] so we can omit it from the
  # resources statement
  resources :users, except: [:new]

  # Login actions - to be managed by the sessions controller
  #  1.  Login validation
  get 'login', to: 'sessions#new'
  #
  # 2.  Create a session based on successful login.
  #     Recall the HTTP verb "post" denotes creation of a new resource
  post 'login', to: 'sessions#create'
  #
  # 3. Logout and thus delete a user session
  delete 'logout', to: 'sessions#destroy'
  #
  # ----  Routes for categories
  resources :categories
end

app/views/layouts/_messages.html.erb
<!-- Add display of flash messages, if there are any -->
<div class="container">
  <% flash.each do |type, msg| %>
    <% if type == 'alert' %>
      <% message_type = 'alert-danger' %>
    <% elsif type == 'warning' %>
      <% message_type = 'alert-warning' %>
    <% elsif type == 'notice' %>
      <% message_type = 'alert-success' %>
    <% else %>
      <% message_type = 'alert-secondary' %>
    <% end %>

    <div class="alert <%= message_type %> alert-dismissible fade show" role="alert">
      &#9757; <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "AlphaBlog", root_path, class: "navbar-brand", id: "logo" %>
      <button class="navbar-toggler" type="button"                                          data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button"
            data-bs-toggle="dropdown" aria-expanded="false">
            Articles
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "Articles Listing", articles_path, class:"dropdown-item" %></li>
            <% if logged_in? %>
              <li><%= link_to 'New_Article', new_article_path, class:"dropdown-item" %></li>
            <% end %>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to "Categories Listing", categories_path, class:"dropdown-item" %></li>
            <% if logged_in? %>
              <li><%= link_to 'New_Category', new_category_path, class:"dropdown-item" %></li>
            <% end %>
          </ul>
        </li>

        <li class="nav-item">
          <%= link_to "Bloggers", users_path, class: "nav-link" %>
        </li>

        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button"
              data-bs-toggle="dropdown" aria-expanded="false">
              <%= "(Admin)" if current_user.admin? %> Profile [<%= current_user.username %>]
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "View your profile", user_path(current_user),
                              class:"dropdown-item" %></li>
              <li><%= link_to 'Edit your profile', edit_user_path(current_user),
                              class:"dropdown-item" %></li>
              <li><hr class="dropdown-divider"></li>
              <li><%= link_to 'Delete your profile', user_path(current_user),
                              class:"dropdown-item text-danger",
                              data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %></li>
            </ul>
          </li>

          <li class="nav-item">
            <%= link_to "LogOut", logout_path, class: "nav-link",
                        data: { "turbo-method": :delete } %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "LogIn", login_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "SignUp", signup_path, class: "nav-link" %>
          </li>
        <% end %>

        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" %>
        </li>

      </ul>

      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-secondary" type="submit">Search</button>
      </form>

    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Alpharich</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <!-- <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %> -->
  </head>

  <body class="d-flex flex-column">
    <!-- The render statements below effectively include the referenced partial files here-->
    <%= render 'layouts/navbar' %>

    <div class = "container" id="page-backer">

      <%= render 'layouts/messages' %>

      <%= yield %>

      <%= render 'shared/footer' %>

    </div>
  </body>
</html>